-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 12:49:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UserDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UserDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UserDB` DEFAULT CHARACTER SET utf8 ;
USE `UserDB` ;

-- -----------------------------------------------------
-- Table `UserDB`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`userinfo` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `userinfoName` VARCHAR(45) NOT NULL,
  `userinfoEmail` VARCHAR(45) NOT NULL,
  `userinfoPassword` VARCHAR(45) NOT NULL,
  `userinfoPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  UNIQUE INDEX `userinfoEmail_UNIQUE` (`userinfoEmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDB`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`log` (
  `logID` INT NOT NULL AUTO_INCREMENT,
  `logTimeStamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `logLocation` VARCHAR(45) NOT NULL,
  `logDestination` VARCHAR(45) NULL,
  `userinfo_userID` INT NOT NULL,
  PRIMARY KEY (`logID`),
  UNIQUE INDEX `logID_UNIQUE` (`logID` ASC),
  INDEX `fk_log_userinfo_idx` (`userinfo_userID` ASC),
  CONSTRAINT `fk_log_userinfo`
    FOREIGN KEY (`userinfo_userID`)
    REFERENCES `UserDB`.`userinfo` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
