-- MySQL Script generated by MySQL Workbench
-- Fri Apr  6 12:51:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wareHouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wareHouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wareHouse` DEFAULT CHARACTER SET utf8 ;
USE `wareHouse` ;

-- -----------------------------------------------------
-- Table `wareHouse`.`previousUpdate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wareHouse`.`previousUpdate` (
  `previousUpdateID` INT NOT NULL AUTO_INCREMENT,
  `previousUpdateFile` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`previousUpdateID`),
  UNIQUE INDEX `previousUpdateID_UNIQUE` (`previousUpdateID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wareHouse`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wareHouse`.`admin` (
  `adminID` INT NOT NULL AUTO_INCREMENT,
  `adminUser` VARCHAR(45) NOT NULL,
  `adminPassword` VARCHAR(45) NOT NULL,
  `adminEmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`adminID`),
  UNIQUE INDEX `adminID_UNIQUE` (`adminID` ASC),
  UNIQUE INDEX `adminUser_UNIQUE` (`adminUser` ASC),
  UNIQUE INDEX `adminPassword_UNIQUE` (`adminPassword` ASC),
  UNIQUE INDEX `adminEmail_UNIQUE` (`adminEmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wareHouse`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wareHouse`.`feedback` (
  `feedbackID` INT NOT NULL AUTO_INCREMENT,
  `feedback` LONGTEXT NOT NULL,
  `feedbackUser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`feedbackID`),
  UNIQUE INDEX `feedbackID_UNIQUE` (`feedbackID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wareHouse`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wareHouse`.`log` (
  `logID` INT NOT NULL AUTO_INCREMENT,
  `logAction` LONGTEXT NOT NULL,
  `logtTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `previousUpdate_previousUpdateID` INT NULL,
  `admin_adminID` INT NULL,
  `feedback_feedbackID` INT NULL,
  PRIMARY KEY (`logID`),
  UNIQUE INDEX `logID_UNIQUE` (`logID` ASC),
  INDEX `fk_log_previousUpdate_idx` (`previousUpdate_previousUpdateID` ASC),
  INDEX `fk_log_admin1_idx` (`admin_adminID` ASC),
  INDEX `fk_log_feedback1_idx` (`feedback_feedbackID` ASC),
  CONSTRAINT `fk_log_previousUpdate`
    FOREIGN KEY (`previousUpdate_previousUpdateID`)
    REFERENCES `wareHouse`.`previousUpdate` (`previousUpdateID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_log_admin1`
    FOREIGN KEY (`admin_adminID`)
    REFERENCES `wareHouse`.`admin` (`adminID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_log_feedback1`
    FOREIGN KEY (`feedback_feedbackID`)
    REFERENCES `wareHouse`.`feedback` (`feedbackID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
